---
bibliography: ../lahteet.bib
csl: ../bratislava.csl
numbersections: true
---


<article id='topbar'>

<a href='javascript:void(0)' id='menu1' class='menulauncher' >Aspekti- ja liikeverbiteoria |</a>
<div class='invisible menubox' id='menu1box'>
<a href='../index.html'>Sisällys</a>
<a href='kurssin_esittely.html'>Kurssin esittely</a>
<a href='kurssin_aikataulu.html'>Kurssin aikataulu</a>
<a href='https://learning2.uta.fi/course/view.php?id=7339'>Moodle</a>
</div>

<a href='javascript:void(0)' id='menu2' class='menulauncher' >Aspekti |</a>
<div class='invisible menubox' id='menu2box'>
<a href='invariantit_merkitykset.html'>Aspektuaalisuus ja aspektin invariantit merkitykset</a>
<a href='aspektin_muodostus.html'>Aspektin/aspektiparin muodostaminen sekä aspektin valintaan vaikuttavat tekijät</a>
<a href='erityismerkitykset.html'>Aspektien erityismerkitykset</a>
</div>

<a href='javascript:void(0)' id='menu3' class='menulauncher' >Aspektin vaikuttavat tekijät vuorovaikutuksessa</a>
<div class='invisible menubox' id='menu3box'>
<a href='aspekti_menneen_ajan_verbimuodoilla.html'>Aspekti menneen ajan verbimuodoilla</a>
<a href='aspekti_futuurisilla_verbimuodoilla.html'>Aspekti futuurin verbimuodoilla</a>
<a href='imperatiivi.html'>Aspekti imperatiivissa</a>
<a href='infinitiivi.html'>Aspekti infinitiivissä</a>
</div>

<script>
function showmenu(obj) {

    // .position() uses position relative to the offset parent, 
    var pos = $(obj).position();

    // .outerWidth() takes into account border and padding.
    var width = $(obj).outerWidth();
    var height = $(obj).outerHeight();
    var menuid = "#" + $(obj).attr('id') + 'box';

    //show the menu directly over the placeholder
    $(menuid).css({
        position: "absolute",
        top: pos.top + height + "px",
        left: (pos.left) + "px"
    }).show();
    
}

$('.menulauncher').hover(function(event) {showmenu(this); });
$('.menubox').mouseleave(function(event) {$('.menubox').hide();});

</script>

</article>

<article class='container'>

<section class='main'>

<p class='header'>Aspekti imperatiivimuodoilla</p>


Aspektin käyttöön imperatiivimuodoissa liittyy eräitä ominaispiirteitä. Tästä
huolimatta myös tavalliset aspektien väliset erot ovat edelleen läsnä.

# Imperatiivi ja yleiset aspektuaaliset erot[^rassudova]

Aivan kuten indikatiivissa, myös imperatiivissa kummallakin aspektilla pätevät
aspektien [invarianttien merkitysten yhteydessä](invariantit_merkitykset.html#monis-maar)
määritellyt tyypilliset, epätyypilliset ja mahdottomat piirteet.
Perfektiiviselle aspektille on edelleen ominaista ilmaista sisäisesti rajattua,
totaalista toimintaa ja imperfektiivisen aspektin osalta toiminnan rajattuus
jätetään edelleen auki, niin että tyypillistä ovat prosessuaalisuus ja toisto.

[^rassudova]: Tämän osion esimerkit peräisin Rassudovalta [-@rassudova1984],
ellei toisin mainita.

Konkreettis-faktisen ja konkreettis-prosessuaalisen merkityksen
välinen normaali ero näkyy virkkeissä @ee_kfmkpm1--@ee_kfmkpm2:

(@ee_kfmkpm1) Поработай, а потом пойдем гулять.
(@ee_kfmkpm2) Стойте здесь, никуда не уходите.

Esimerkissä @ee_kfmkpm1 perfektiivinen aspekti ilmaisee kahta toimintaa, joiden
sisäiset rajat on selvästi hahmotettavissa. Tämä korostuu siinä, että kyseessä
on peräkkäisten toimintojan sarja. 

Esimerkissä @ee_kfmkpm2 esitetään myös kaksi toimintaa, mutta on hyvin selvää,
ettei toimintojen kestoon tai totaalisuuteen oteta kantaa, vaan kyseessä on
kaksi jotakuinkin samanaikaista ja määrittelemättömän kestoista toimintaa.

Myös konkreettis-faktisen ja rajattoman toiston erityismerkitysten välinen
oppositio toteutuu normaalisti imperatiivissa. Tämä näkyy esimerkeissä
@ee_kfmrt1--@ee_kfmrt2:

(@ee_kfmrt1) Перед началом работы проветрите комнату
(@ee_kfmrt2) Перед началом работы проветривайте комнату

Esimerkissä @ee_kfmrt2 imperfektiivinen aspekti tuo mukanaan toiminnan
tulkitsemisen toistuvana.

# Modaaliset erot imperatiivin käytössä

Imperatiivin aspektin käyttöön liittyvät ominaispiirteet johtuvat sävyeroista,
joita valinta I:n ja P:n välillä aiheuttaa. Tärkeään rooliin merkitysten
tulkinnassa nousevat sekä konteksti että intonaatio [@rassudova1984, 178].

<div class='definition'>
<div class='defheader'>Määritelmä 1.</div> 
Aspektien välinen perusero on, että imperfektiivisen verbin imperatiivimuoto on
kauttaaltaan neutraalimpi ja ikään kuin pyytää viestin vastaanottajaa tekemään
vähemmän tai *vähemmän yllättäviä* asioita kuin perfektiivisen aspektin
imperatiivimuoto. Perfektiivisen aspektin verbit puolestaan usein sisältävät
tiukemman pyynnön tai käskyn ja niillä on todellista sisältöä, eikä niitä
käytetä ainoastaan retorisesti tai sosiaalisten konventioiden täyttämiseksi.
Imperfektiivisen aspektin käskymuodoissa on usein kyse *kehotuksesta* tai
rajoitetummissa tapauksissa *neuvosta* tai *toiveesta*, kun taas perfektiivisen
aspektin imperatiivimuodot ovat usein selkeämmin *pyyntöjä* tai varsinaisia
*käskyjä*.
</div>

## Retorinen kehotus vai pyyntö

Tarkastellaan aspektien  välistä peruseroa esimerkkien @ee_lento1I--@ee_lentoP
avulla.

(@ee_lento1I) Проходите, пожалуйста. 

Esimerkin @ee_lento1I kehotukselle voidaan kuvitella kontekstiksi, että
lentokentällä on juuri annettu kuulutus tietyn lennon matkustajille, että
koneeseen voi nousta. Kuulutuksen jälkeen ovella seisova lentoemäntä toistaa
muodollisesti kehotuksen käydä eteenpäin kohti istumapaikkoja. Vastaavasti
esimerkissä @ee_lentoP voidaan ajatella, että joku matkustajista seisoo keskellä
matkustamon käytävää, ja lentoemäntä pyytää häntä siirtymään ja menemään
paikalleen:

(@ee_lentoP) Пройдите, пожалуйста, на своё место.

Esimerkissä @ee_lentoP kyseessä ei ole vain retorinen kehotus, vaan selkeä
pyyntö, jonka toteuttamiseksi pyynnön kohteen on toimittava tavalla,
joka tuo selkeän muutoksen siihen, miten hän olisi toiminut ilman pyyntöä.

Asiakaspalvelutilanteissa vastaava retorisen kehotuksen ja pyynnön ero tulee
usein ilmi. Jos asiakas lähestyy myyjää tennismailahyllyn luona ja pyytää
näyttämään vaihtoehtoja, myyjä saattaa vastata imperfektiivisen aspektin
verbillä:

(@ee_valitse) ­- Вот такие у нас есть.. Выбирайте!

Jos taas asiakas astuu suureen tavarataloon, jossa myyjä ei voi etukäteen
tietää, onko asiakas etsimässä urheiluvarusteita vai juhlavaatteita, asiakkaan
pyyntö myyjälle on loogista esittää perfektiivisen aspektin verbillä:

(@ee_tennis) -- Пожалуйста, покажите мне теннисные ракетки.

Imperfektiivisen aspektin neutraali luonne näkyy siinä, että puhuja voi ilmaista
välinpitämättömyytensä tai neutraalin suhtautumisensa johonkin pyyntöön
käyttämällä imperfektiivistä aspektia:

(@ee_eivalia) -- Я хочу сходить сегодня к Саше. - Ну что же, <span class='r'>иди.</span>


## Odotettu tai mainittu toiminta

Imperfektiivisen aspektin imperatiivi pitää usein sisällään ajatuksen siitä,
että toiminta on jollain tapaa odotettua ja jossain mielessä voisi toteutua myös
ilman erillistä pyyntöä. Tämä tulee ilmi, kun vertaa esimerkkejä @ee_odotI ja
@ee_odotP:

(@ee_odotI) Как прошел экзамен? Рассказывай!
(@ee_odotP) Расскажи, как прошел экзамен.

Esimerkissä @ee_odotI kehotuksen kohde osaa odottaa pyyntöä ja kummatkin
dialogin osapuolista ikään kuin olettavat, että asiasta tullaan puhumaan -- se on
kummankin mielessä. Sen sijaan esimerkki @ee_odotP on sisällöltään
vastaanottajalle yllättävämpi/odottamattomampi, eikä ennen virkkeen @ee_odotP
lausumista ollut selvää, mistä asiasta tullaan puhumaan.

Tässä suhteessa aspektit toimivat imperatiivissa eri tavoin kuin
[edellä](aspekti_menneen_ajan_verbimuodoilla.html#odotettusuor)
tarkasteltaessa menneessä ajassa tapahtuvaa kerrontaa vastaanottajalta
odotetusta toiminnasta. Vertaa esimerkkejä @ee_mennyt_odotettutoim_imp ja
@ee_mennyt_odotettutoim_imp2:

(@ee_mennyt_odotettutoim_imp) Ты помыл посуду?
(@ee_mennyt_odotettutoim_imp2) Ты помыл посуду? Нет? Ну, давай, <span class='r'>мой</span>!

Odotetun toiminnan käsitteeseen liittyy myös ajatus siitä, että jokin pyyntö
ikään kuin "leijuu ilmassa" ja odottaa vastaustaan. Tällöin ensimmäinen pyyntö
on saatettu esittää perfektiivisellä aspektilla, mutta kun vastausta ei kuulu,
kehotus toistetaan imperfektiivisellä aspektilla. Samantapainen tilanne on
läsnä, kun kehotuksen kohde epäröi tai ujostelee kehottajan mielestä ilman
syytä:

(@ee_sisaan) -- <span class='r'>Войдите.....</span> Ну что же ты? Не бойся, <span class='r'>входи</span>, входи! (@ee_lue) - Читайте, читайте, вы мне не мешаете.
(@ee_lue) -- Возьмите.. Берите, берите, у меня есть еще одня ручка.

Sama ilmiö on nähtävissä myös, kun kehottaja käy
kärsimättömäksi:

(@ee_kirjoita) -- <span class='r'>Запиши</span> мой телефон... <span class='r'>Записывай</span>, пожалуйста, я очень тороплюсь.


## Neuvo tai toive

Imperfektiivisen aspektin imperatiivin tyypillinen rooli odotettuna kehotuksena
näkyy myös, kun pohditaan, mitä jossakin asiassa tulisi tehdä, ja päädytään
johonkin vaihtoehtoon, josta on jo aiemmin keskusteltu:

(@ee_neuvo) Я думал, как вам поступить? Знаете, что? 
<span class='r'>Соглашайтесь</span>, поезжайте в новое место! 

Jos neuvo tulee ikään kuin pyytämättä ja odottamatta, perfektiivinen aspekti on
todennäköinen:

(@ee_neuvoP) -- Проиграй нарочно, посмотрим, как он на это реагирует.

Jos imperatiivilla ilmaistava pyyntö on ennemminkin toive, käyteään myös
imperfektiivistä aspektia:

(@ee_toive) -- Приходи сегодня домой пораньше.

# Imperfektisen aspektin erityispiirteitä

Kun huomio kiinnitetään toiminnan tapaan, on todennäköistä käyttää
imperfektiivistä aspektia:

(@ee_tapa) Пиши аккуратнее, а то цифры не разобрать!

Imperfektiivisen aspektin voi ajallisesti katsoa viittaavan välittömään
puhehetkeen ja toiminnan aloittamiseen:

(@ee_valiton) -- Чего вы ждете? Начинайте!
		
# Perfektiivisen aspektin erityispiirteitä

Jos imperatiiviin liittyy muu kuin puhehetkeen viittaava ajanilmaus,
perfektiivinen aspekti on tavallisesti ainoa vaihtoehto:

(@ee_ajanilmaus) -- Сделайте эту работу сегодня / к двум часам / к субботе.
		
Tämä on loogista, kun ajattelee, että ajanilmaus tuo mukanaan ajatuksen siitä,
että toiminta käsitetään totaalisena: sen loppumisen on myös mahduttava
aikamääreen sisälle.

</section>
</article>

