---
title       : Aspekti- ja liikeverbiteoria
author      : Juho Härme
job         : tohtorikoulutettava / käännöstiede venäjä
framework   : revealjs        # {io2012, html5slides, shower, dzslides, ...}
revealjs    : {theme: sky, transition: linear, center: "false"}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : mathjax            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
logo        : slidify_logo.png

---

<link rel="stylesheet" type="text/css" href="tyylit.css">

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<!--
[Kurssin sisällysluettelo](../index.html)
Siirrä tämä ylätunnisteeksi!
-->

# Aspekti- ja liikeverbiteoria, kevät 2016

<br><br><br>

### Kurssin esittely

--- .class &vertical

## Virallisia tavoitteita

<br>

.fragment *Perehdytään aspektiopin <span class='fragment highlight-red'>keskeisiin teoriakäsitteisiin</span>,
<span class='fragment highlight-blue'>aspektiparien muodostukseen</span>, <span class='fragment highlight-red'>aspektien suhteeseen aikakategoriaan ja modaalisuuteen</span>,
<span class='fragment highlight-blue'>käyttöön eri kielenkäyttötilanteissa</span> sekä  <span class='fragment highlight-red'>teonlaatuihin</span> kuuluviin
verbeihin. Syvennetään etuliitteettömien <span class='fragment highlight-blue'>liikeverbien muoto-opillisten ja
semanttisten piirteiden ja sananmuodostuksen tuntemusta</span>. Perehdytään
<span class='fragment highlight-red'>etuliitteellisiin aspektipareihin</span> ja niiden merkityksiin sekä
<span class='fragment highlight-blue'>etuliitteisten liikeverbien teonlaatuihin</span>.*

***

*Opintojakson suoritettuaan opiskelija tuntee hyvin aspekti- ja
liikeverbiteoria<span class='fragment highlight-red'>n</span> sekä osaa soveltaa tietojaan käytännössä*

--- .class &vertical

## Kurssin alustava aikataulu

***

Päivämäärä   | Aihealue         | Aihe
------------ | ---------        | ------
ti 12.1.2016 | Aspektiteoria    | johdanto + invariantit merkitykset
ti 19.1.2016 | Aspektiteoria    | Aspektin muodostus ja aspektin valintaan vaikuttavat tekijät
ti 26.1.2016 | Aspektiteoria    | erityismerkitykset yleisesti
ti 02.2.2016 | Aspektiteoria    | aspekti menneen ajan verbimuodoilla
ti 09.2.2016 | Aspektiteoria    | aspekti menneen ajan verbimuodoilla
ti 16.2.2016 | Aspektiteoria    | aspekti kieltomuodossa
ti 23.2.2016 | Aspektiteoria    | aspekti futuurisilla verbimuodoilla
ti 01.3.2016 | Aspektiteoria    | <span class='b'>TAUKOVIIKKO</span>
ti 08.3.2016 | Aspektiteoria    | aspekti infinitiivissä, aspekti imperatiivissa
ti 15.3.2016 | Aspektiteoria    | teonlaadut
ti 22.3.2016 | Aspektiteoria    | <span class='r'>KOE 1: aspektiteoria</span>

***


Päivämäärä   | Aihealue         | Aihe
------------ | ---------        | ------
ti 29.3.2016 | Liikeverbiteoria | Yleisiä käsitteitä
ti 05.4.2016 | Liikeverbiteoria | Muodostus ja merkityksiä
ti 12.4.2016 | Liikeverbiteoria | Liikeverbit aspektipareina
ti 19.4.2016 | Liikeverbiteoria | Liikeverbien teonlaadut
ti 26.4.2016 | Liikeverbiteoria | <span class='r'>KOE 2: Liikeverbiteoria</span>


---

## Työskentelytavoista

>- Pääasiallinen opetuskieli suomi, mutta...
>- Digitaalista materiaalia
    - Moodle [(linkki)](https://learning2.uta.fi/course/view.php?id=7339)
    - Luentotekstit ja -diat
    - Tulevat myös tulostettavaan / lukulaiteystävälliseen muotoon
>- Korpusesimerkit työkaluna
    - Jokaisella kurssilaisella henkilökohtainen wikisivu, jonne
    - kerätään esimerkkejä <span class='fragment highlight-red'>(ainakin, muttei välttämättä ainoastaan)</span> tunneilla annettavien ohjeitten perusteella 
    - Monet luentomateriaalin esimerkeistä myös korpuksista peräisin
    - wikisivulla (positiivinen) vaikutus arvosanaan
>- Koe kummastakin aihealueesta, painotus aspektissa

<script>
$('ol.incremental li').addClass('fragment')//note to anyone reading this code, you may need to change to ul from ol depending on ordered vs unordered list
$('ul.incremental li').addClass('fragment')//note to anyone reading this code, you may need to change to ul from ol depending on ordered vs unordered list

</script>

